baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "DataFest: COVID-19 Virtual Data Challenge"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeURLs = true
uglyURLs = true
publishDir = "../DataFestUofT.github.io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "ASA DataFest@UofT"
  bio = ""
  job = ""
  location = "University of Toronto"
  gravatarEmail = "gillis.aning@utoronto.ca"
  # Your profile picture
#  picture = ""
  twitter = "UofTStatSci"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
  
[[menu.main]]
  weight = 3
  identifier = "signup"
  name = "Sign Up"
  pre = "<i class='fas fa-user-plus fa-lg'></i>"
  url = "/signup.html"
  
[[menu.main]]
  weight = 2
  identifier = "details"
  name = "Details"
  pre = "<i class=\"material-icons\">description</i>"
  url = "/details.html"

 [[menu.main]]
  weight = 4
  identifier = "resources"
  name = "Resources"
  pre = "<i class=\"material-icons\">help</i>"
  url = "/resources.html"

[[menu.main]]
  weight = 5
  identifier = "sponsors"
  name = "Sponsors"
  pre = "<i class='fas fa-life-ring'></i>"
  url = "/sponsors.html"




[[menu.footer]]
  weight = 1
  identifier = "University of Toronto"
  name = "UofT StatSci"
  pre = "<i class=\"button-icon fa fa fa-map-marker\"></i>"
  url = "https://www.statistics.utoronto.ca/"
[[menu.footer]]
  weight = 2
  name = "ASA DataFest"
  pre = "<i class=\"button-icon fa fa fa-chart-bar\"></i>"
  url = "https://ww2.amstat.org/education/datafest/"
[[menu.footer]]
  weight = 3
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"button-icon fa fa fa-twitter\"></i>"
  url = "https://twitter.com/UofTStatSci"
[[menu.footer]]

[params]
  dateFormat = "January 2, 2006"
  background = "https://www.thetimes.co.uk/imageserver/image/%2Fmethode%2Fsundaytimes%2Fprod%2Fweb%2Fbin%2Ff06e9694-65fb-11ea-b021-fae459863cfa.jpg?crop=8256%2C4644%2C0%2C430&resize=1180"
